---
 
 - hosts: all
   become: true
   pre_tasks:
 
   - name: install updates (Ubuntu)
     tags: always
     apt:
       upgrade: dist
       update_cache: yes
     when: ansible_distribution == "Debian"

 - hosts: web_servers
   become: true
   tasks:

   - name: install apache2 package (Debian)
     tags: apache,apache2,debian
     apt:
       name:
         - apache2
         - libapache2-mod-php
       state: latest
     when: ansible_distribution == "Debian"

   - name: copy default html file to site
     tags: apache,apache2,debian
     copy:
       src: default_site.html
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: 0644
